# Generated by Django 2.2.5 on 2019-09-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=200)),
                ('departure_city', models.CharField(max_length=300)),
                ('destination', models.CharField(max_length=300)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('cabin_class', models.CharField(help_text='First Class, Economy, Premium, All, Business', max_length=200)),
                ('passenger', models.IntegerField(blank=True, null=True)),
                ('number_children', models.IntegerField(blank=True, null=True)),
                ('number_infant', models.IntegerField(blank=True, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('available_seat', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
