# Generated by Django 2.2.5 on 2019-09-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_city', models.CharField(max_length=300)),
                ('destination_city', models.CharField(max_length=300)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('cabin_class', models.CharField(help_text='First Class, Economy, Premium, All, Business', max_length=200)),
                ('number_adults', models.IntegerField()),
                ('number_children', models.IntegerField()),
                ('number_infant', models.IntegerField()),
                ('created', models.DateField(auto_now=True)),
                ('available_seat', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
