# Generated by Django 2.2.5 on 2019-09-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='arrival_time',
            new_name='arrival_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_date',
            field=models.DateTimeField(),
        ),
    ]
