# Generated by Django 2.2.5 on 2019-09-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20190913_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='arrival_date',
            field=models.DateField(),
        ),
    ]
