# Generated by Django 2.2.5 on 2019-09-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20190913_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='arrival_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number_adults',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number_children',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number_infant',
            field=models.IntegerField(blank=True),
        ),
    ]
