# Generated by Django 2.2.5 on 2019-09-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20190914_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='destination_city',
            new_name='destination',
        ),
    ]
