# Generated by Django 2.2.5 on 2019-09-14 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20190914_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='flight_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
