# Generated by Django 2.2.5 on 2019-09-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticket_flight_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='number_adults',
            new_name='passenger',
        ),
    ]
