# Generated by Django 2.2.5 on 2019-09-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20190914_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
